---
# tasks file for minecraft_bedrock_deploy

- name: Create minecraft user
  user:
    name: minecraft
    state: present
    comment: Minecraft service account
  become: true

- name: Add current user to {{ service_account }} group
  user:
    name: "{{ ansible_user }}"
    groups:
      - "{{ service_account }}"
    append: yes
  become: true

- name: Create Folders
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0775"
  with_items:
    - "{{ tmp_dir }}"
    - "{{ unpack_dir }}"
    - "{{ minecraft_install_path }}"
  become: true

- name: Install Packages RedHat
  yum:
    name: java-11-openjdk
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install Packages Debian
  apt:
    name:
      - openjdk-11-jdk
      - libcurl4
      - unzip
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Create minecraft service
  template:
    src: templates/minecraft_service.j2
    dest: "/etc/systemd/system/{{ minecraft_server_name }}_minecraft.service"
  become: true
  register: create_service

- name: Create server start script
  template:
    src: templates/minecraft_service_script.j2
    dest: "{{ minecraft_install_path }}start_{{ minecraft_server_name }}_minecraft.sh"
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: +x
  become: true

- name: reload systemd
  command: systemctl daemon-reload
  become: true
  when: create_service.changed

- name: Download Minecraft Bedrock {{ minecraft_version }}
  get_url:
    url: https://minecraft.azureedge.net/bin-linux/bedrock-server-{{ minecraft_version }}.zip
    dest: "{{ tmp_dir }}"
    mode: "0775"
  become: true

- name: Unpack Minecraft Bedrock
  unarchive:
    src: "{{ tmp_dir }}bedrock-server-{{ minecraft_version }}.zip"
    dest: "{{ unpack_dir }}"
    remote_src: true
  become: true

- name: Customize server.properties
  include_tasks: server_properties.yml

- name: Template permissions.json file
  template:
    src: templates/permissions.json.j2
    dest: "{{ unpack_dir }}permissions.json"
  when:
    - operator_accounts is defined

- name: Template whitelist.json file
  template:
    src: templates/whitelist.json.j2
    dest: "{{ unpack_dir }}/whitelist.json"
  when:
    - whitelist_accounts is defined

- name: Put Minecraft files into install directory
  copy:
    src: "{{ unpack_dir }}"
    dest: "{{ minecraft_install_path }}"
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    remote_src: true
    force: true
  become: true

- name: Make bedrock_server executable
  file:
    path: "{{ minecraft_install_path }}bedrock_server"
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: +x

- name: Start new minecraft service
  service:
    name: "{{ minecraft_server_name }}_minecraft.service"
    enabled: true
    state: started
  become: true
