---
# deploy file for minecraft_bedrock_connect

- name: Create Folders
  file:
    state: directory
    path: /etc/bedrock_connect
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0775"

- name: Get latest bedrock connect release .jar file
  uri:
    url: https://api.github.com/repos/Pugmatt/BedrockConnect/releases/latest
    return_content: true
  register: json_response

- name: Download the bedrock connect jar file
  get_url:
    url: "{{ json_response.json.assets[0].browser_download_url }}"
    dest: /etc/bedrock_connect/{{ json_response.json.assets[0].name }}
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0775"

- name: Modify firewalld configuration for bedrock connect ports
  ansible.posix.firewalld:
    port: 19132/udp
    permanent: yes
    state: enabled
  when:
    - ansible_os_family == 'RedHat'
    - install_bedrock_connect is true

- name: Create bedrock connect service script
  template:
    src: templates/bedrock_connect_script.j2
    dest: /etc/bedrock_connect/start_bedrockconnect
    owner: "{{ service_account }}"
    mode: "0775"

- name: Create bedrock connect service
  template:
    src: templates/bedrock_connect_service.j2
    dest: /etc/systemd/system/bedrock_connect.service
    mode: +x
  register: create_service

- name: reload systemd
  command: systemctl daemon-reload
  become: true
  when: create_service.changed

- name: Start new bedrock connect service
  service:
    name: bedrock_connect.service
    enabled: true
    state: started
  become: true
